uit = uitable
f = figure;
uit = uitable(f,'Data',randi(100,10,3),'Position',[20 20 262 204]);
uit = uitable(f,'Data',randi(100,10,3),'Position',[20 20 362 304]);
f = figure;
uit = uitable(f);
d = {'Male',52,true;'Male',40,true;'Female',25,false};
uit.Data = d;
uit.ColumnEditable = true;
uit.ColumnName = {'Gender','Age','Authorized'};
uit.ColumnEditable = true;
title_cells = TitleCells';
data_cells = DataCells';
figure = 1;
f = figure;
uit = uitable(f);
uit.Data = data_cells
uit.ColumnName = title_cells
uit.ColumnEditable = true;
uit.Position = [20 20 362 304];